version: "3"

services:
  flask_api:
    container_name: flask_api
    image: food_flask_api:v1
    networks:
      - food_app

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "5050:80"
    depends_on:
      - flask_api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/usr/share/nginx/html
    networks:
      - food_app

networks:
  food_app: